[2025-04-19T19:28:23.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-19T19:28:23.992+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_spark_submit_dag.run_test_spark_script manual__2025-04-19T19:28:23.045394+00:00 [queued]>
[2025-04-19T19:28:24.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_spark_submit_dag.run_test_spark_script manual__2025-04-19T19:28:23.045394+00:00 [queued]>
[2025-04-19T19:28:24.008+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-19T19:28:24.040+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): run_test_spark_script> on 2025-04-19 19:28:23.045394+00:00
[2025-04-19T19:28:24.056+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2041) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-19T19:28:24.059+0000] {standard_task_runner.py:63} INFO - Started process 2042 to run task
[2025-04-19T19:28:24.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_spark_submit_dag', 'run_test_spark_script', 'manual__2025-04-19T19:28:23.045394+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/test_spark_submit_dag.py', '--cfg-path', '/tmp/tmpfbb7btiw']
[2025-04-19T19:28:24.063+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask run_test_spark_script
[2025-04-19T19:28:24.081+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-19T19:28:24.109+0000] {task_command.py:426} INFO - Running <TaskInstance: test_spark_submit_dag.run_test_spark_script manual__2025-04-19T19:28:23.045394+00:00 [running]> on host c78215a515b5
[2025-04-19T19:28:24.171+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_spark_submit_dag' AIRFLOW_CTX_TASK_ID='run_test_spark_script' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T19:28:23.045394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-19T19:28:23.045394+00:00'
[2025-04-19T19:28:24.171+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-19T19:28:24.244+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-19T19:28:24.245+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.app.name=TestSparkSubmit --name arrow-spark --verbose --deploy-mode client /opt/bitnami/spark/work/log_dummy_job.py
[2025-04-19T19:28:24.351+0000] {spark_submit.py:644} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-19T19:28:24.352+0000] {spark_submit.py:644} INFO - JAVA_HOME is not set
[2025-04-19T19:28:24.352+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-19T19:28:24.360+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.app.name=TestSparkSubmit --name arrow-spark --verbose --deploy-mode client /opt/bitnami/spark/work/log_dummy_job.py. Error code is: 1.
[2025-04-19T19:28:24.368+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=test_spark_submit_dag, task_id=run_test_spark_script, run_id=manual__2025-04-19T19:28:23.045394+00:00, execution_date=20250419T192823, start_date=20250419T192823, end_date=20250419T192824
[2025-04-19T19:28:24.376+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task run_test_spark_script (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.app.name=TestSparkSubmit --name arrow-spark --verbose --deploy-mode client /opt/bitnami/spark/work/log_dummy_job.py. Error code is: 1.; 2042)
[2025-04-19T19:28:24.400+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-19T19:28:24.417+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-19T19:28:24.418+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
