[2025-04-16T16:02:57.764+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-16T16:02:57.878+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: log_etl_dag.run_spark_analytics manual__2025-04-16T16:02:56.507260+00:00 [queued]>
[2025-04-16T16:02:57.906+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: log_etl_dag.run_spark_analytics manual__2025-04-16T16:02:56.507260+00:00 [queued]>
[2025-04-16T16:02:57.907+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-16T16:02:57.951+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_analytics> on 2025-04-16 16:02:56.507260+00:00
[2025-04-16T16:02:57.980+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=318) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-16T16:02:57.982+0000] {standard_task_runner.py:63} INFO - Started process 319 to run task
[2025-04-16T16:02:57.984+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'log_etl_dag', 'run_spark_analytics', 'manual__2025-04-16T16:02:56.507260+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/log_etl_dag.py', '--cfg-path', '/tmp/tmp3bvhwxv6']
[2025-04-16T16:02:58.000+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask run_spark_analytics
[2025-04-16T16:02:58.083+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-16T16:02:58.184+0000] {task_command.py:426} INFO - Running <TaskInstance: log_etl_dag.run_spark_analytics manual__2025-04-16T16:02:56.507260+00:00 [running]> on host b9cb4e70916b
[2025-04-16T16:02:58.526+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='log_etl_dag' AIRFLOW_CTX_TASK_ID='run_spark_analytics' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T16:02:56.507260+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T16:02:56.507260+00:00'
[2025-04-16T16:02:58.529+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-16T16:02:58.614+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-16T16:02:58.616+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark-master spark-submit --master spark://spark-master:7077 /opt/bitnami/spark/work/log_analytics.py']
[2025-04-16T16:02:58.651+0000] {subprocess.py:86} INFO - Output:
[2025-04-16T16:02:58.844+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2025-04-16T16:02:58.846+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-16T16:02:58.847+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-16T16:02:58.857+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-16T16:02:58.864+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=log_etl_dag, task_id=run_spark_analytics, run_id=manual__2025-04-16T16:02:56.507260+00:00, execution_date=20250416T160256, start_date=20250416T160257, end_date=20250416T160258
[2025-04-16T16:02:58.881+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task run_spark_analytics (Bash command failed. The command returned a non-zero exit code 1.; 319)
[2025-04-16T16:02:58.927+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-16T16:02:58.941+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-16T16:02:58.942+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
